import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import type { Env } from "../index";
import type { ExportRequest, ExportResponse, Block } from "../types";

export const exportRoutes = new Hono<{ Bindings: Env }>();

const exportSchema = z.object({
  canvas: z.object({
    blocks: z.array(z.any()),
    connections: z.array(z.any()),
  }),
  language: z.enum(["discord.js", "discord.py"]),
  settings: z.object({
    prefix: z.string(),
    botToken: z.string(),
    clientId: z.string(),
    intents: z.array(z.number()),
  }),
});

// POST /api/export - Generate bot code
exportRoutes.post("/", zValidator("json", exportSchema), async (c) => {
  try {
    const data = c.req.valid("json") as ExportRequest;

    const isJs = data.language === "discord.js";
    const files = [];
    const dependencies: Record<string, string> = {};

    // Generate main file
    const mainCode = generateMainFile(data, isJs);
    files.push({
      path: isJs ? "index.js" : "main.py",
      content: mainCode,
    });

    // Generate .env file
    files.push({
      path: ".env",
      content: generateEnvFile(data.settings),
    });

    // Generate package.json or requirements.txt
    if (isJs) {
      dependencies["discord.js"] = "^14.14.1";
      dependencies["dotenv"] = "^16.4.5";

      files.push({
        path: "package.json",
        content: JSON.stringify(
          {
            name: "discord-bot",
            version: "1.0.0",
            main: "index.js",
            dependencies,
            scripts: {
              start: "node index.js",
            },
          },
          null,
          2,
        ),
      });
    } else {
      files.push({
        path: "requirements.txt",
        content: "discord.py==2.3.2\npython-dotenv==1.0.0",
      });
    }

    // Generate README
    files.push({
      path: "README.md",
      content: generateReadme(data.language),
    });

    const response: ExportResponse = {
      files,
      dependencies,
      instructions: generateInstructions(data.language),
    };

    return c.json(response);
  } catch (error) {
    return c.json({ error: "Export failed" }, 500);
  }
});

function generateMainFile(data: ExportRequest, isJs: boolean): string {
  const blocks = data.canvas.blocks;

  if (isJs) {
    return `const { Client, GatewayIntentBits } = require('discord.js');
require('dotenv').config();

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages]
});

client.once('ready', () => {
  console.log('Bot is online!');
});

${generateCommands(blocks, true)}

client.login(process.env.BOT_TOKEN);`;
  } else {
    return `import discord
from discord.ext import commands
import os
from dotenv import load_dotenv

load_dotenv()

bot = commands.Bot(command_prefix='!', intents=discord.Intents.all())

@bot.event
async def on_ready():
    print(f'Bot is online as {bot.user}')

${generateCommands(blocks, false)}

bot.run(os.getenv('BOT_TOKEN'))`;
  }
}

function generateCommands(blocks: Block[], isJs: boolean): string {
  const commandBlocks = blocks.filter((b) => b.type === "command_slash");
  let code = "";

  for (const block of commandBlocks) {
    const name = block.data.properties.name || "ping";
    if (isJs) {
      code += `\nclient.on('interactionCreate', async (interaction) => {
  if (!interaction.isChatInputCommand()) return;
  if (interaction.commandName === '${name}') {
    await interaction.reply('Command executed!');
  }
});\n`;
    } else {
      code += `\n@bot.tree.command(name="${name}", description="Command")
async def ${name}(interaction: discord.Interaction):
    await interaction.response.send_message('Command executed!')\n`;
    }
  }

  return code;
}

function generateEnvFile(settings: any): string {
  return `BOT_TOKEN=${settings.botToken}
CLIENT_ID=${settings.clientId}
PREFIX=${settings.prefix}`;
}

function generateReadme(language: string): string {
  return `# Discord Bot

## Setup

1. Install dependencies:
${language === "discord.js" ? "   npm install" : "   pip install -r requirements.txt"}

2. Configure .env file with your bot token

3. Run the bot:
${language === "discord.js" ? "   npm start" : "   python main.py"}

## Generated by Botify
`;
}

function generateInstructions(language: string): string {
  return `## Deployment Instructions

1. Install dependencies
2. Set environment variables
3. Run bot locally to test
4. Deploy to your preferred hosting platform

Generated from Botify visual canvas.`;
}
