import { BlockDefinition, BlockType, BlockCategory } from '@/types'

export const BLOCK_DEFINITIONS: Record<BlockType, BlockDefinition> = {
  // ==================== TRIGGERS ====================

  command_slash: {
    type: 'command_slash',
    label: 'Slash Command',
    category: 'triggers',
    description: 'Triggered when a user runs a slash command /name',
    icon: 'Terminal',
    color: '#8B5CF6',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Command Name',
        type: 'text',
        required: true,
        defaultValue: 'ping',
        placeholder: 'ping',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'text',
        required: true,
        defaultValue: 'My cool command',
      },
      { key: 'options', label: 'Options', type: 'options_list', required: false, defaultValue: [] },
      {
        key: 'permissions',
        label: 'Required Permission',
        type: 'select',
        required: false,
        defaultValue: null,
        options: [
          { label: 'None (Public)', value: 'null' },
          { label: 'Administrator', value: 'Administrator' },
          { label: 'Manage Server', value: 'ManageGuild' },
          { label: 'Manage Channels', value: 'ManageChannels' },
          { label: 'Kick Members', value: 'KickMembers' },
          { label: 'Ban Members', value: 'BanMembers' },
        ],
      },
    ],
  },

  // ==================== NEW PERMISSION CONDITIONS ====================

  condition_has_role: {
    type: 'condition_has_role',
    label: 'Has Role?',
    category: 'conditions',
    description: 'Check user role',
    icon: 'Shield',
    color: '#6366F1',
    inputs: 1,
    outputs: 2,
    properties: [{ key: 'roleId', label: 'Role ID', type: 'text', required: true }],
  },

  condition_has_permission: {
    type: 'condition_has_permission',
    label: 'Has Permission?',
    category: 'conditions',
    description: 'Check permissions',
    icon: 'Lock',
    color: '#6366F1',
    inputs: 1,
    outputs: 2,
    properties: [
      {
        key: 'permission',
        label: 'Permission',
        type: 'select',
        required: true,
        options: [
          { label: 'Administrator', value: 'Administrator' },
          { label: 'Manage Server', value: 'ManageGuild' },
          { label: 'Manage Messages', value: 'ManageMessages' },
        ],
      },
    ],
  },

  command_subcommand: {
    type: 'command_subcommand',
    label: 'Subcommand',
    category: 'triggers',
    description: 'Subcommand like /cmd sub',
    icon: 'GitBranch',
    color: '#8B5CF6',
    inputs: 0,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'text', required: true },
    ],
  },

  // ==================== TRIGGERS: MENUS ====================

  context_menu_user: {
    type: 'context_menu_user',
    label: 'On User Right-Click',
    category: 'triggers',
    description: 'Triggered when right-clicking a user (Apps > Command)',
    icon: 'User',
    color: '#8B5CF6',
    inputs: 0,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Menu Name', type: 'text', required: true, placeholder: 'Poke User' },
    ],
  },

  context_menu_message: {
    type: 'context_menu_message',
    label: 'On Message Right-Click',
    category: 'triggers',
    description: 'Triggered when right-clicking a message (Apps > Command)',
    icon: 'MessageSquare',
    color: '#8B5CF6',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Menu Name',
        type: 'text',
        required: true,
        placeholder: 'Translate Message',
      },
    ],
  },

  // ==================== LEGACY / OTHER ====================

  command_user: {
    type: 'command_user',
    label: 'User Command (Legacy)',
    category: 'triggers',
    description: 'Legacy user command',
    icon: 'User',
    color: '#64748B',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  command_message: {
    type: 'command_message',
    label: 'Message Command (Legacy)',
    category: 'triggers',
    description: 'Legacy message command',
    icon: 'MessageSquare',
    color: '#64748B',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_listener: {
    type: 'event_listener',
    label: 'Event Listener',
    category: 'events',
    description: 'Listen to any Discord event',
    icon: 'Zap',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'event',
        label: 'Event Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Message Created', value: 'messageCreate' },
          { label: 'Member Joined', value: 'guildMemberAdd' },
          { label: 'Member Left', value: 'guildMemberRemove' },
          { label: 'Reaction Added', value: 'messageReactionAdd' },
          { label: 'Ready', value: 'ready' },
        ],
      },
    ],
  },

  event_ready: {
    type: 'event_ready',
    label: 'Bot Ready',
    category: 'events',
    description: 'When bot comes online',
    icon: 'Power',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_message_create: {
    type: 'event_message_create',
    label: 'Message Sent',
    category: 'events',
    description: 'When a message is sent',
    icon: 'MessageCircle',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_message_delete: {
    type: 'event_message_delete',
    label: 'Message Deleted',
    category: 'events',
    description: 'When message is deleted',
    icon: 'Trash2',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_message_update: {
    type: 'event_message_update',
    label: 'Message Edited',
    category: 'events',
    description: 'When message edited',
    icon: 'Edit',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_member_join: {
    type: 'event_member_join',
    label: 'Member Join',
    category: 'events',
    description: 'User joins server',
    icon: 'UserPlus',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_member_leave: {
    type: 'event_member_leave',
    label: 'Member Leave',
    category: 'events',
    description: 'User leaves server',
    icon: 'UserMinus',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_member_update: {
    type: 'event_member_update',
    label: 'Member Update',
    category: 'events',
    description: 'Member roles/nick changed',
    icon: 'UserCheck',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_role_create: {
    type: 'event_role_create',
    label: 'Role Create',
    category: 'events',
    description: 'Role created',
    icon: 'Shield',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_role_delete: {
    type: 'event_role_delete',
    label: 'Role Delete',
    category: 'events',
    description: 'Role deleted',
    icon: 'ShieldOff',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_role_update: {
    type: 'event_role_update',
    label: 'Role Update',
    category: 'events',
    description: 'Role updated',
    icon: 'Shield',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_channel_create: {
    type: 'event_channel_create',
    label: 'Channel Create',
    category: 'events',
    description: 'Channel created',
    icon: 'Hash',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_channel_delete: {
    type: 'event_channel_delete',
    label: 'Channel Delete',
    category: 'events',
    description: 'Channel deleted',
    icon: 'Trash',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_channel_update: {
    type: 'event_channel_update',
    label: 'Channel Update',
    category: 'events',
    description: 'Channel updated',
    icon: 'Edit',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_reaction_add: {
    type: 'event_reaction_add',
    label: 'Reaction Add',
    category: 'events',
    description: 'Reaction added',
    icon: 'Smile',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  event_reaction_remove: {
    type: 'event_reaction_remove',
    label: 'Reaction Remove',
    category: 'events',
    description: 'Reaction removed',
    icon: 'Frown',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_button_click: {
    type: 'event_button_click',
    label: 'Button Click',
    category: 'events',
    description: 'Any button clicked',
    icon: 'MousePointer',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  on_button_click: {
    type: 'on_button_click',
    label: 'On specific Button',
    category: 'events',
    description: 'Specific button clicked',
    icon: 'MousePointer',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'customId', label: 'Button ID', type: 'text', required: true }],
  },

  event_select_menu: {
    type: 'event_select_menu',
    label: 'Select Menu',
    category: 'events',
    description: 'Any menu used',
    icon: 'List',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  on_select_menu: {
    type: 'on_select_menu',
    label: 'On specific Menu',
    category: 'events',
    description: 'Specific menu used',
    icon: 'List',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'customId', label: 'Menu ID', type: 'text', required: true }],
  },

  event_modal_submit: {
    type: 'event_modal_submit',
    label: 'Modal Submit',
    category: 'events',
    description: 'Any modal submitted',
    icon: 'FileText',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [],
  },
  on_modal_submit: {
    type: 'on_modal_submit',
    label: 'On specific Modal',
    category: 'events',
    description: 'Specific modal submitted',
    icon: 'FileText',
    color: '#10B981',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'customId', label: 'Modal ID', type: 'text', required: true }],
  },

  // ==================== ACTIONS ====================

  // ==================== ACTIONS: INTERACTIONS ====================

  action_reply: {
    type: 'action_reply',
    label: 'Reply to Interaction',
    category: 'actions',
    description: 'Reply to the slash command or button',
    icon: 'MessageSquare',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'content',
        label: 'Message Content',
        type: 'textarea',
        required: true,
        defaultValue: 'Hello world!',
      },
      {
        key: 'ephemeral',
        label: 'Hidden (Ephemeral)?',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
      {
        key: 'tts',
        label: 'Text-to-Speech?',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  defer_reply: {
    type: 'action_reply', // Reusing logic roughly
    label: 'Defer Reply',
    category: 'actions',
    description: 'Show "Bot is thinking..."',
    icon: 'Loader',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'ephemeral', label: 'Hidden?', type: 'boolean', required: false, defaultValue: false },
    ],
  },

  edit_reply: {
    type: 'edit_message',
    label: 'Edit Reply',
    category: 'actions',
    description: 'Edit the initial response',
    icon: 'Edit',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'content', label: 'New Content', type: 'textarea', required: true }],
  },

  follow_up: {
    type: 'send_message',
    label: 'Follow Up Message',
    category: 'actions',
    description: 'Send another message after reply',
    icon: 'CornerDownRight',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'content', label: 'Content', type: 'textarea', required: true },
      { key: 'ephemeral', label: 'Hidden?', type: 'boolean', required: false, defaultValue: false },
    ],
  },

  // ==================== ACTIONS: MESSAGES & EMBEDS ====================

  send_message: {
    type: 'send_message',
    label: 'Send Message (Channel)',
    category: 'actions',
    description: 'Send a message to a specific channel',
    icon: 'Send',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channel_id',
        label: 'Channel ID',
        type: 'text',
        required: true,
        placeholder: '1234567890...',
      },
      { key: 'content', label: 'Content', type: 'textarea', required: true },
      {
        key: 'attachment',
        label: 'File Attachment',
        type: 'file',
        required: false,
        helperText: 'Max size: 25MB. Supported: images, docs, etc.',
      },
    ],
  },

  send_embed: {
    type: 'send_embed',
    label: 'Send Embed',
    category: 'actions',
    description: 'Send a rich embed message',
    icon: 'Layout',
    color: '#E91E63',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'title', label: 'Title', type: 'text', required: false },
      { key: 'description', label: 'Description', type: 'textarea', required: false },
      {
        key: 'color',
        label: 'Color (Hex)',
        type: 'color',
        required: false,
        defaultValue: '#5865F2',
      },
      { key: 'url', label: 'URL', type: 'text', required: false },
      { key: 'image', label: 'Image URL', type: 'text', required: false },
      { key: 'thumbnail', label: 'Thumbnail URL', type: 'text', required: false },
      { key: 'author_name', label: 'Author Name', type: 'text', required: false },
      { key: 'author_icon', label: 'Author Icon URL', type: 'text', required: false },
      { key: 'footer_text', label: 'Footer Text', type: 'text', required: false },
      { key: 'footer_icon', label: 'Footer Icon URL', type: 'text', required: false },
      {
        key: 'timestamp',
        label: 'Add Timestamp?',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
      {
        key: 'attachment',
        label: 'File Attachment',
        type: 'file',
        required: false,
        helperText: 'Max size: 25MB. Supported: images, docs, etc.',
      },
    ],
  },

  edit_message: {
    type: 'edit_message',
    label: 'Edit Message',
    category: 'actions',
    description: 'Edit a message',
    icon: 'Edit3',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'content', label: 'New Content', type: 'textarea', required: true }],
  },

  delete_message: {
    type: 'delete_message',
    label: 'Delete Message',
    category: 'actions',
    description: 'Delete this message',
    icon: 'Trash',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [],
  },

  // ==================== ACTIONS: MODERATION ====================

  action_ban: {
    type: 'action_ban',
    label: 'Ban Member',
    category: 'moderation',
    description: 'Ban a user from the server',
    icon: 'Gavel',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'user_id',
        label: 'User ID',
        type: 'text',
        required: true,
        placeholder: 'User to ban',
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'text',
        required: false,
        placeholder: 'Rule violation',
      },
      {
        key: 'delete_days',
        label: 'Delete Msgs (Days)',
        type: 'number',
        required: false,
        defaultValue: 0,
      },
    ],
  },

  action_kick: {
    type: 'action_kick',
    label: 'Kick Member',
    category: 'moderation',
    description: 'Kick a user from the server',
    icon: 'UserMinus',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'user_id', label: 'User ID', type: 'text', required: true },
      { key: 'reason', label: 'Reason', type: 'text', required: false },
    ],
  },

  action_timeout: {
    type: 'action_timeout',
    label: 'Timeout Member',
    category: 'moderation',
    description: 'Mute user for duration',
    icon: 'Clock',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'user_id', label: 'User ID', type: 'text', required: true },
      {
        key: 'duration',
        label: 'Duration (Minutes)',
        type: 'number',
        required: true,
        defaultValue: 60,
      },
      { key: 'reason', label: 'Reason', type: 'text', required: false },
    ],
  },

  action_purge: {
    type: 'action_purge', // Ensure this is in types
    label: 'Purge Messages',
    category: 'moderation',
    description: 'Delete multiple messages',
    icon: 'Layers',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'amount',
        label: 'Amount (max 100)',
        type: 'number',
        required: true,
        defaultValue: 10,
      },
      {
        key: 'filter',
        label: 'Filter',
        type: 'select',
        required: true,
        options: [
          { label: 'All', value: 'all' },
          { label: 'Bots Only', value: 'bots' },
          { label: 'Users Only', value: 'users' },
        ],
      },
    ],
  },

  action_role_add: {
    type: 'action_role_add',
    label: 'Add Role',
    category: 'moderation',
    description: 'Give a role to user',
    icon: 'Shield',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'user_id', label: 'User ID', type: 'text', required: true },
      { key: 'role_id', label: 'Role ID', type: 'text', required: true },
    ],
  },

  action_role_remove: {
    type: 'action_role_remove',
    label: 'Remove Role',
    category: 'moderation',
    description: 'Remove role from user',
    icon: 'ShieldOff',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'user_id', label: 'User ID', type: 'text', required: true },
      { key: 'role_id', label: 'Role ID', type: 'text', required: true },
    ],
  },

  // ==================== ACTIONS: CHANNELS & THREADS ====================

  create_channel: {
    type: 'create_channel',
    label: 'Create Channel',
    category: 'actions',
    description: 'Create a new channel',
    icon: 'Hash',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Channel Name', type: 'text', required: true },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Text', value: '0' },
          { label: 'Voice', value: '2' },
        ],
      },
      { key: 'topic', label: 'Topic', type: 'text', required: false },
    ],
  },

  delete_channel: {
    type: 'delete_channel',
    label: 'Delete Channel',
    category: 'actions',
    description: 'Delete a channel',
    icon: 'Trash2',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'channel_id', label: 'Channel ID', type: 'text', required: true }],
  },

  thread_create: {
    type: 'thread_create', // Matching types
    label: 'Create Thread',
    category: 'actions',
    description: 'Start a new thread',
    icon: 'GitPullRequest',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Thread Name', type: 'text', required: true },
      { key: 'channel_id', label: 'Parent Channel ID', type: 'text', required: true },
      {
        key: 'auto_archive',
        label: 'Archive After (Min)',
        type: 'select',
        required: true,
        options: [
          { label: '1 Hour', value: '60' },
          { label: '24 Hours', value: '1440' },
        ],
      },
    ],
  },

  // ==================== ACTIONS: VOICE ====================

  voice_mute: {
    type: 'voice_mute',
    label: 'Mute Member',
    category: 'actions', // or voice category if exists
    description: 'Server mute a user',
    icon: 'MicOff',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'user_id', label: 'User ID', type: 'text', required: true },
      { key: 'state', label: 'Muted?', type: 'boolean', required: true, defaultValue: true },
    ],
  },

  // ==================== COMPONENTS ====================

  add_button: {
    type: 'add_button',
    label: 'Add Button',
    category: 'components',
    description: 'Attach a button to the message',
    icon: 'MousePointer',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'label', label: 'Label', type: 'text', required: true, placeholder: 'Click me' },
      {
        key: 'customId',
        label: 'Custom ID',
        type: 'text',
        required: true,
        placeholder: 'btn_click_1',
      },
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        required: true,
        defaultValue: 'Primary',
        options: [
          { label: 'Primary (Blurple)', value: 'Primary' },
          { label: 'Secondary (Grey)', value: 'Secondary' },
          { label: 'Success (Green)', value: 'Success' },
          { label: 'Danger (Red)', value: 'Danger' },
          { label: 'Link (URL)', value: 'Link' },
        ],
      },
      { key: 'emoji', label: 'Emoji', type: 'text', required: false, placeholder: '🔥' },
      { key: 'url', label: 'URL (if Link style)', type: 'text', required: false },
      {
        key: 'disabled',
        label: 'Disabled?',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  add_select_menu: {
    type: 'add_select_menu',
    label: 'Add Select Menu',
    category: 'components',
    description: 'Attach a dropdown menu',
    icon: 'List',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Custom ID',
        type: 'text',
        required: true,
        placeholder: 'menu_select_1',
      },
      {
        key: 'placeholder',
        label: 'Placeholder Text',
        type: 'text',
        required: false,
        placeholder: 'Select an option...',
      },
      {
        key: 'min_values',
        label: 'Min Selections',
        type: 'number',
        required: false,
        defaultValue: 1,
      },
      {
        key: 'max_values',
        label: 'Max Selections',
        type: 'number',
        required: false,
        defaultValue: 1,
      },
      {
        key: 'disabled',
        label: 'Disabled?',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
      // Note: Options would typically be a dynamic list builder, keeping simple for now
    ],
  },

  show_modal: {
    type: 'show_modal',
    label: 'Show Modal (Form)',
    category: 'components',
    description: 'Display a popup form to the user',
    icon: 'AppWindow',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'title', label: 'Modal Title', type: 'text', required: true, placeholder: 'My Form' },
      {
        key: 'customId',
        label: 'Modal ID',
        type: 'text',
        required: true,
        placeholder: 'modal_submit_1',
      },
      {
        key: 'text_input_label',
        label: 'Input 1 Label',
        type: 'text',
        required: true,
        placeholder: 'What is your name?',
      },
      {
        key: 'text_input_id',
        label: 'Input 1 ID',
        type: 'text',
        required: true,
        placeholder: 'name_input',
      },
      {
        key: 'text_input_style',
        label: 'Input 1 Style',
        type: 'select',
        required: true,
        defaultValue: 'Short',
        options: [
          { label: 'Short (Line)', value: 'Short' },
          { label: 'Paragraph (Box)', value: 'Paragraph' },
        ],
      },
    ],
  },

  // ==================== LOGIC ====================

  if_condition: {
    type: 'if_condition',
    label: 'If Condition',
    category: 'logic',
    description: 'Branch based on value',
    icon: 'GitBranch',
    color: '#6366F1',
    inputs: 1,
    outputs: 2,
    properties: [{ key: 'condition', label: 'Condition', type: 'text', required: true }],
  },

  loop: {
    type: 'loop',
    label: 'Loop',
    category: 'logic',
    description: 'Repeat actions',
    icon: 'Repeat',
    color: '#6366F1',
    inputs: 1,
    outputs: 2,
    properties: [{ key: 'times', label: 'Count', type: 'number', required: true, defaultValue: 1 }],
  },
  for_loop: {
    type: 'for_loop',
    label: 'For Loop',
    category: 'logic',
    description: 'Iterate list',
    icon: 'Repeat',
    color: '#6366F1',
    inputs: 1,
    outputs: 2,
    properties: [],
  },
  wait: {
    type: 'wait',
    label: 'Wait',
    category: 'logic',
    description: 'Delay',
    icon: 'Clock',
    color: '#6366F1',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'ms', label: 'Milliseconds', type: 'number', required: true, defaultValue: 1000 },
    ],
  },
  random: {
    type: 'random',
    label: 'Random',
    category: 'logic',
    description: 'Random Number',
    icon: 'Shuffle',
    color: '#6366F1',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  error_handler: {
    type: 'error_handler',
    label: 'On Error',
    category: 'logic',
    description: 'Catch errors',
    icon: 'AlertTriangle',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  set_variable: {
    type: 'set_variable',
    label: 'Set Var',
    category: 'data',
    description: 'Save value',
    icon: 'Save',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
    ],
  },
  get_variable: {
    type: 'get_variable',
    label: 'Get Var',
    category: 'data',
    description: 'Load value',
    icon: 'Database',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Name', type: 'text', required: true }],
  },
  math_operation: {
    type: 'math_operation',
    label: 'Math',
    category: 'data',
    description: 'Calculate',
    icon: 'Calculator',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  console_log: {
    type: 'console_log',
    label: 'Log',
    category: 'advanced',
    description: 'Print to console',
    icon: 'Terminal',
    color: '#6B7280',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'message', label: 'Message', type: 'text', required: true }],
  },

  // ==================== MODERATION ====================

  // Duplicates removed (action_kick, action_ban, etc are defined above)
  member_timeout: {
    type: 'member_timeout',
    label: 'Timeout Member',
    category: 'moderation',
    description: 'Timeout',
    icon: 'Clock',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'duration', label: 'Duration', type: 'number', required: true }],
  },
  member_add_role: {
    type: 'member_add_role',
    label: 'Add Role Member',
    category: 'roles',
    description: 'Add Role',
    icon: 'Plus',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'role', label: 'Role', type: 'text', required: true }],
  },
  member_remove_role: {
    type: 'member_remove_role',
    label: 'Remove Role Member',
    category: 'roles',
    description: 'Remove Role',
    icon: 'Minus',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'role', label: 'Role', type: 'text', required: true }],
  },

  // ==================== ADVANCED ====================

  http_request: {
    type: 'http_request',
    label: 'HTTP Request',
    category: 'advanced',
    description: 'Make API Call',
    icon: 'Globe',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 2,
    properties: [{ key: 'url', label: 'URL', type: 'text', required: true }],
  },
  webhook_send: {
    type: 'webhook_send',
    label: 'Webhook',
    category: 'advanced',
    description: 'Send webhook',
    icon: 'Webhook',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'url', label: 'URL', type: 'text', required: true }],
  },
  database_get: {
    type: 'database_get',
    label: 'DB Get',
    category: 'data',
    description: 'Get DB',
    icon: 'Database',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  database_set: {
    type: 'database_set',
    label: 'DB Set',
    category: 'data',
    description: 'Set DB',
    icon: 'Save',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },

  // ==================== FUNCTIONS ====================
  call_module: {
    type: 'call_module',
    label: 'Call Module',
    category: 'advanced',
    description: 'Run another module',
    icon: 'Layers',
    color: '#EC4899',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'moduleId',
        label: 'Select Module',
        type: 'module_select',
        required: true,
      },
      {
        key: 'await',
        label: 'Await Result?',
        type: 'boolean',
        required: false,
        defaultValue: true,
      },
    ],
  },

  database_store: {
    type: 'database_store',
    label: 'DB Store',
    category: 'data',
    description: 'Store DB',
    icon: 'Save',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  database_retrieve: {
    type: 'database_retrieve',
    label: 'DB Retrieve',
    category: 'data',
    description: 'Get DB',
    icon: 'Database',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  parse_json: {
    type: 'parse_json',
    label: 'Parse JSON',
    category: 'data',
    description: 'Parse',
    icon: 'Code',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  stringify_json: {
    type: 'stringify_json',
    label: 'Stringify JSON',
    category: 'data',
    description: 'Stringify',
    icon: 'Code',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },

  voice_join: {
    type: 'voice_join',
    label: 'Voice Join',
    category: 'voice',
    description: 'Join VC',
    icon: 'Mic',
    color: '#06B6D4',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  voice_leave: {
    type: 'voice_leave',
    label: 'Voice Leave',
    category: 'voice',
    description: 'Leave VC',
    icon: 'MicOff',
    color: '#06B6D4',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  // Duplicate voice_mute removed
  voice_play_audio: {
    type: 'voice_play_audio',
    label: 'Play Audio',
    category: 'voice',
    description: 'Play',
    icon: 'Play',
    color: '#06B6D4',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'url', label: 'URL', type: 'text', required: true }],
  },

  // Duplicate thread_create removed
  thread_join: {
    type: 'thread_join',
    label: 'Join Thread',
    category: 'channels',
    description: 'Join thread',
    icon: 'MessageSquare',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  thread_archive: {
    type: 'thread_archive',
    label: 'Archive Thread',
    category: 'channels',
    description: 'Archive thread',
    icon: 'Archive',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },

  create_role: {
    type: 'create_role',
    label: 'Create Role',
    category: 'roles',
    description: 'Make role',
    icon: 'Plus',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Name', type: 'text', required: true }],
  },
  role_create: {
    type: 'role_create',
    label: 'Create Role',
    category: 'roles',
    description: 'Make role',
    icon: 'Plus',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Name', type: 'text', required: true }],
  },
  // Duplicates removed (create_channel, delete_channel defined above)

  check_permissions: {
    type: 'check_permissions',
    label: 'Check Perms',
    category: 'permissions',
    description: 'Check perms',
    icon: 'Lock',
    color: '#F59E0B',
    inputs: 1,
    outputs: 2,
    properties: [{ key: 'perm', label: 'Permission', type: 'text', required: true }],
  },
  check_bot_permissions: {
    type: 'check_bot_permissions',
    label: 'Bot Perms',
    category: 'permissions',
    description: 'Check bot perms',
    icon: 'Lock',
    color: '#F59E0B',
    inputs: 1,
    outputs: 2,
    properties: [],
  },

  automod_alert: {
    type: 'automod_alert',
    label: 'AutoMod Alert',
    category: 'moderation',
    description: 'Alert',
    icon: 'Shield',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  automod_rule_create: {
    type: 'automod_rule_create',
    label: 'Create Rule',
    category: 'moderation',
    description: 'Rule',
    icon: 'Shield',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  event_schedule: {
    type: 'event_schedule',
    label: 'Schedule Event',
    category: 'events',
    description: 'Schedule',
    icon: 'Calendar',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  event_cancel: {
    type: 'event_cancel',
    label: 'Cancel Event',
    category: 'events',
    description: 'Cancel',
    icon: 'X',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  stage_start: {
    type: 'stage_start',
    label: 'Start Stage',
    category: 'voice',
    description: 'Stage',
    icon: 'Mic',
    color: '#06B6D4',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  stage_end: {
    type: 'stage_end',
    label: 'End Stage',
    category: 'voice',
    description: 'Stage',
    icon: 'MicOff',
    color: '#06B6D4',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  invite_create: {
    type: 'invite_create',
    label: 'Create Invite',
    category: 'channels',
    description: 'Invite',
    icon: 'Link',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  sticker_send: {
    type: 'sticker_send',
    label: 'Send Sticker',
    category: 'actions',
    description: 'Sticker',
    icon: 'Smile',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  emoji_add: {
    type: 'emoji_add',
    label: 'Add Emoji',
    category: 'actions',
    description: 'Emoji',
    icon: 'Smile',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  // ==================== LOGIC EXTENDED ====================

  string_manipulation: {
    type: 'string_manipulation',
    label: 'String Ops',
    category: 'data',
    description: 'Split/Join/Replace',
    icon: 'Type',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        required: true,
        options: [
          { label: 'Split', value: 'split' },
          { label: 'Join', value: 'join' },
          { label: 'Replace', value: 'replace' },
          { label: 'To Upper', value: 'upper' },
          { label: 'To Lower', value: 'lower' },
        ],
      },
      { key: 'input', label: 'Input', type: 'text', required: true },
    ],
  },

  math_advanced: {
    type: 'math_advanced',
    label: 'Adv Math',
    category: 'data',
    description: 'Advanced Ops',
    icon: 'Calculator',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        required: true,
        options: [
          { label: 'Power', value: 'pow' },
          { label: 'Root', value: 'sqrt' },
          { label: 'Round', value: 'round' },
          { label: 'Random Range', value: 'random_range' },
        ],
      },
    ],
  },

  channel_create: {
    type: 'channel_create',
    label: 'Create Channel',
    category: 'actions',
    description: 'Create a new channel',
    icon: 'Hash',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Channel Name', type: 'text', required: true },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Text', value: '0' },
          { label: 'Voice', value: '2' },
        ],
      },
      { key: 'topic', label: 'Topic', type: 'text', required: false },
    ],
  },
}

// Export categories for the block library
export const BLOCK_CATEGORIES: Array<{
  id: BlockCategory
  label: string
  icon: string
  color: string
}> = [
  { id: 'triggers', label: 'Triggers', icon: 'Zap', color: '#8B5CF6' },
  { id: 'events', label: 'Events', icon: 'Radio', color: '#10B981' },
  { id: 'messages', label: 'Messages', icon: 'Send', color: '#3B82F6' },
  { id: 'components', label: 'Components', icon: 'Layout', color: '#EC4899' },
  { id: 'moderation', label: 'Moderation', icon: 'Shield', color: '#EF4444' },
  { id: 'roles', label: 'Roles', icon: 'Users', color: '#F59E0B' },
  { id: 'channels', label: 'Channels', icon: 'Hash', color: '#8B5CF6' },
  { id: 'voice', label: 'Voice', icon: 'Mic', color: '#06B6D4' },
  { id: 'logic', label: 'Logic', icon: 'GitBranch', color: '#6366F1' },
  { id: 'data', label: 'Data', icon: 'Database', color: '#14B8A6' },
  { id: 'permissions', label: 'Permissions', icon: 'Lock', color: '#F59E0B' },
  { id: 'advanced', label: 'Advanced', icon: 'Zap', color: '#8B5CF6' },
  { id: 'actions', label: 'Actions', icon: 'Play', color: '#3B82F6' },
  { id: 'conditions', label: 'Conditions', icon: 'GitBranch', color: '#6366F1' },
  { id: 'variables', label: 'Variables', icon: 'Database', color: '#14B8A6' },
  { id: 'replies', label: 'Replies', icon: 'Reply', color: '#3B82F6' },
]
