import { BlockDefinition, BlockType, BlockCategory } from '@/types'

export const BLOCK_DEFINITIONS: Record<BlockType, BlockDefinition> = {
  // --- TRIGGERS ---
  command_slash: {
    type: 'command_slash',
    label: '/ Command',
    description: 'Universal slash command entry point.',
    category: 'triggers',
    icon: 'Terminal',
    color: '#6366f1',
    inputs: 0,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'ping' },
      { key: 'description', label: 'Description', type: 'text', required: true },
      { key: 'nsfw', label: 'NSFW Access', type: 'boolean', required: false, defaultValue: false },
    ],
  },
  command_sub: {
    type: 'command_sub',
    label: 'Subcommand',
    description: 'Nesting logic for command groups.',
    category: 'triggers',
    icon: 'ChevronRight',
    color: '#818cf8',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'text', required: true },
    ],
  },
  event_listener: {
    type: 'event_listener',
    label: 'Event',
    description: 'Listen for gateway events.',
    category: 'triggers',
    icon: 'Zap',
    color: '#f59e0b',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'event',
        label: 'Event Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Message Sent', value: 'messageCreate' },
          { label: 'Member Joined', value: 'guildMemberAdd' },
          { label: 'Reaction Added', value: 'messageReactionAdd' },
          { label: 'Voice Status Change', value: 'voiceStateUpdate' },
          { label: 'Thread Created', value: 'threadCreate' },
          { label: 'Invite Created', value: 'inviteCreate' },
          { label: 'AutoMod Rule Triggered', value: 'autoModerationActionExecution' },
        ],
      },
    ],
  },
  on_button_click: {
    type: 'on_button_click',
    label: 'Button Press',
    description: 'Interactive button intercept.',
    category: 'triggers',
    icon: 'MousePointer2',
    color: '#db2777',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'customId', label: 'Component ID', type: 'text', required: true }],
  },
  on_select_menu: {
    type: 'on_select_menu',
    label: 'Menu Select',
    description: 'Dropdown menu interaction.',
    category: 'triggers',
    icon: 'List',
    color: '#ec4899',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'customId', label: 'Menu ID', type: 'text', required: true }],
  },
  on_modal_submit: {
    type: 'on_modal_submit',
    label: 'Modal Submit',
    description: 'Form submission intercept.',
    category: 'triggers',
    icon: 'Maximize',
    color: '#ec4899',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'customId', label: 'Modal ID', type: 'text', required: true }],
  },
  command_user: {
    type: 'command_user',
    label: 'User Menu',
    description: 'User profile context command.',
    category: 'triggers',
    icon: 'UserSquare',
    color: '#6366f1',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'name', label: 'Name', type: 'text', required: true }],
  },
  command_message: {
    type: 'command_message',
    label: 'Msg Menu',
    description: 'Message context command.',
    category: 'triggers',
    icon: 'MessageSquare',
    color: '#6366f1',
    inputs: 0,
    outputs: 1,
    properties: [{ key: 'name', label: 'Name', type: 'text', required: true }],
  },

  // --- CORE LOGIC ---
  if_condition: {
    type: 'if_condition',
    label: 'Condition',
    description: 'Logical branch for data evaluation.',
    category: 'logic',
    icon: 'GitBranch',
    color: '#fbbf24',
    inputs: 1,
    outputs: 2,
    properties: [
      { key: 'varA', label: 'Left Operand', type: 'text', required: true },
      {
        key: 'op',
        label: 'Operator',
        type: 'select',
        required: true,
        defaultValue: 'equals',
        options: [
          { label: '==', value: 'equals' },
          { label: '!=', value: 'not_equals' },
          { label: '>', value: 'gt' },
          { label: '<', value: 'lt' },
          { label: 'Contains', value: 'contains' },
        ],
      },
      { key: 'varB', label: 'Right Operand', type: 'text', required: true },
    ],
  },
  for_loop: {
    type: 'for_loop',
    label: 'Iterator',
    description: 'Iterative loop over collections.',
    category: 'logic',
    icon: 'RefreshCw',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'list', label: 'Collection', type: 'text', required: true },
      { key: 'itemName', label: 'Variable', type: 'text', required: true, defaultValue: 'item' },
    ],
  },
  wait: {
    type: 'wait',
    label: 'Delay',
    description: 'Pause thread execution.',
    category: 'logic',
    icon: 'Hourglass',
    color: '#94a3b8',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'duration', label: 'Seconds', type: 'number', required: true, defaultValue: 1 },
    ],
  },
  error_handler: {
    type: 'error_handler',
    label: 'Error Trap',
    description: 'Catch and handle exceptions.',
    category: 'logic',
    icon: 'ShieldAlert',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'logError', label: 'Log Error', type: 'boolean', required: false, defaultValue: true },
    ],
  },
  set_variable: {
    type: 'set_variable',
    label: 'Set Variable',
    description: 'Store data in memory.',
    category: 'data',
    icon: 'Variable',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Key', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
    ],
  },
  get_variable: {
    type: 'get_variable',
    label: 'Get Variable',
    description: 'Retrieve data from memory.',
    category: 'data',
    icon: 'Database',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Key', type: 'text', required: true }],
  },
  math_operation: {
    type: 'math_operation',
    label: 'Math',
    description: 'Calculate numerical values.',
    category: 'logic',
    icon: 'Percent',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'expression', label: 'Formula', type: 'text', required: true }],
  },

  // --- ACTIONS ---
  send_message: {
    type: 'send_message',
    label: 'Send Message',
    description: 'Send text content to channel.',
    category: 'actions',
    icon: 'Send',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'content', label: 'Content', type: 'textarea', required: true },
      {
        key: 'ephemeral',
        label: 'Ephemeral',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },
  edit_message: {
    type: 'edit_message',
    label: 'Edit Message',
    description: 'Modify an existing message.',
    category: 'actions',
    icon: 'Edit3',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'messageId', label: 'Message ID', type: 'text', required: true },
      { key: 'content', label: 'New Content', type: 'textarea', required: true },
    ],
  },
  delete_message: {
    type: 'delete_message',
    label: 'Delete Message',
    description: 'Remove message from channel.',
    category: 'actions',
    icon: 'Trash2',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'messageId', label: 'Message ID', type: 'text', required: true }],
  },
  send_embed: {
    type: 'send_embed',
    label: 'Send Embed',
    description: 'Dispatch a rich structured block.',
    category: 'actions',
    icon: 'LayoutTemplate',
    color: '#0ea5e9',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'title', label: 'Title', type: 'text', required: false },
      { key: 'description', label: 'Description', type: 'textarea', required: false },
      { key: 'color', label: 'Hex Color', type: 'color', required: false, defaultValue: '#6366f1' },
    ],
  },
  add_button: {
    type: 'add_button',
    label: 'Attach Button',
    description: 'Append button to current interaction.',
    category: 'actions',
    icon: 'Plus',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'customId', label: 'ID', type: 'text', required: true },
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        required: true,
        defaultValue: 'primary',
        options: [
          { label: 'Primary', value: 'primary' },
          { label: 'Success', value: 'success' },
          { label: 'Danger', value: 'danger' },
        ],
      },
    ],
  },
  add_select_menu: {
    type: 'add_select_menu',
    label: 'Attach Menu',
    description: 'Append dropdown to interaction.',
    category: 'actions',
    icon: 'List',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'customId', label: 'ID', type: 'text', required: true }],
  },
  show_modal: {
    type: 'show_modal',
    label: 'Show Modal',
    description: 'Display a popup form.',
    category: 'actions',
    icon: 'Maximize',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'customId', label: 'ID', type: 'text', required: true },
    ],
  },
  action_reply: {
    type: 'action_reply',
    label: 'Reply',
    description: 'Responsive interaction reply.',
    category: 'actions',
    icon: 'CornerUpRight',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'content', label: 'Content', type: 'textarea', required: true }],
  },

  // --- MODERATION ---
  action_role_add: {
    type: 'action_role_add',
    label: 'Add Role',
    description: 'Grant role to member.',
    category: 'moderation',
    icon: 'UserPlus',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'roleId', label: 'Role ID', type: 'text', required: true },
    ],
  },
  action_role_remove: {
    type: 'action_role_remove',
    label: 'Remove Role',
    description: 'Strip role from member.',
    category: 'moderation',
    icon: 'UserMinus',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'roleId', label: 'Role ID', type: 'text', required: true },
    ],
  },
  action_kick: {
    type: 'action_kick',
    label: 'Kick',
    description: 'Remove user from guild.',
    category: 'moderation',
    icon: 'UserMinus',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'reason', label: 'Reason', type: 'text', required: false },
    ],
  },
  action_ban: {
    type: 'action_ban',
    label: 'Ban',
    description: 'Persistent guild exclusion.',
    category: 'moderation',
    icon: 'Lock',
    color: '#dc2626',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'reason', label: 'Reason', type: 'text', required: false },
    ],
  },
  action_timeout: {
    type: 'action_timeout',
    label: 'Timeout',
    description: 'Temporary user isolation.',
    category: 'moderation',
    icon: 'Clock',
    color: '#f97316',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'duration', label: 'Minutes', type: 'number', required: true },
    ],
  },

  // --- DATA & API ---
  http_request: {
    type: 'http_request',
    label: 'HTTP Request',
    description: 'Fetch external service data.',
    category: 'data',
    icon: 'Globe',
    color: '#0ea5e9',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'url', label: 'Endpoint', type: 'text', required: true },
      {
        key: 'method',
        label: 'Verb',
        type: 'select',
        required: true,
        options: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
        ],
      },
    ],
  },
  parse_json: {
    type: 'parse_json',
    label: 'Parse JSON',
    description: 'String to object conversion.',
    category: 'data',
    icon: 'FileCode',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'input', label: 'Source', type: 'text', required: true }],
  },
  stringify_json: {
    type: 'stringify_json',
    label: 'JSON String',
    description: 'Object to string conversion.',
    category: 'data',
    icon: 'FileText',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'input', label: 'Source', type: 'text', required: true }],
  },
  database_get: {
    type: 'database_get',
    label: 'DB Get',
    description: 'Persistent storage retrieval.',
    category: 'data',
    icon: 'Database',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'key', label: 'Key', type: 'text', required: true }],
  },
  database_set: {
    type: 'database_set',
    label: 'DB Set',
    description: 'Persistent storage write.',
    category: 'data',
    icon: 'Database',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'key', label: 'Key', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
    ],
  },

  // --- ADVANCED & DISCORD API ---
  voice_join: {
    type: 'voice_join',
    label: 'Join Voice',
    description: 'Connect to a voice channel.',
    category: 'advanced',
    icon: 'Volume2',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'channelId', label: 'Channel ID', type: 'text', required: true }],
  },
  voice_leave: {
    type: 'voice_leave',
    label: 'Leave Voice',
    description: 'Disconnect from voice.',
    category: 'advanced',
    icon: 'VolumeX',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  voice_mute: {
    type: 'voice_mute',
    label: 'Mute Member',
    description: 'Toggle voice mute.',
    category: 'advanced',
    icon: 'MicOff',
    color: '#f97316',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'mute', label: 'Muted', type: 'boolean', required: true, defaultValue: true },
    ],
  },
  thread_create: {
    type: 'thread_create',
    label: 'Create Thread',
    description: 'Initiate a message thread.',
    category: 'advanced',
    icon: 'Hash',
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Name', type: 'text', required: true }],
  },
  thread_join: {
    type: 'thread_join',
    label: 'Join Thread',
    description: 'Participate in thread.',
    category: 'advanced',
    icon: 'UserPlus',
    color: '#a855f7',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'threadId', label: 'Thread ID', type: 'text', required: true }],
  },
  thread_archive: {
    type: 'thread_archive',
    label: 'Archive Thread',
    description: 'Lock thread history.',
    category: 'advanced',
    icon: 'Archive',
    color: '#94a3b8',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'threadId', label: 'Thread ID', type: 'text', required: true }],
  },
  automod_alert: {
    type: 'automod_alert',
    label: 'AutoMod Alert',
    description: 'Trigger system alert.',
    category: 'moderation',
    icon: 'ShieldAlert',
    color: '#f97316',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'message', label: 'Log Message', type: 'text', required: true }],
  },
  automod_rule_create: {
    type: 'automod_rule_create',
    label: 'AutoMod Rule',
    description: 'Deploy new guard rule.',
    category: 'moderation',
    icon: 'Shield',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Rule Name', type: 'text', required: true }],
  },
  event_schedule: {
    type: 'event_schedule',
    label: 'Schedule Event',
    description: 'Guild scheduled event.',
    category: 'advanced',
    icon: 'Calendar',
    color: '#34d399',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Event Name', type: 'text', required: true },
      { key: 'startTime', label: 'ISO Start', type: 'text', required: true },
    ],
  },
  event_cancel: {
    type: 'event_cancel',
    label: 'Cancel Event',
    description: 'Void scheduled event.',
    category: 'advanced',
    icon: 'CalendarX',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'eventId', label: 'Event ID', type: 'text', required: true }],
  },
  stage_start: {
    type: 'stage_start',
    label: 'Start Stage',
    description: 'Initiate stage session.',
    category: 'advanced',
    icon: 'Mic2',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'topic', label: 'Topic', type: 'text', required: true }],
  },
  stage_end: {
    type: 'stage_end',
    label: 'End Stage',
    description: 'Terminate stage session.',
    category: 'advanced',
    icon: 'MicOff',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    properties: [],
  },
  invite_create: {
    type: 'invite_create',
    label: 'Invoke Invite',
    description: 'Generate access link.',
    category: 'advanced',
    icon: 'UserPlus',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'channelId', label: 'Channel ID', type: 'text', required: true }],
  },
  sticker_send: {
    type: 'sticker_send',
    label: 'Send Sticker',
    description: 'Dispatch image asset.',
    category: 'advanced',
    icon: 'Image',
    color: '#db2777',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'stickerId', label: 'Sticker ID', type: 'text', required: true }],
  },
  emoji_add: {
    type: 'emoji_add',
    label: 'Create Emoji',
    description: 'Upload custom asset.',
    category: 'advanced',
    icon: 'Smile',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'url', label: 'Image URL', type: 'text', required: true },
    ],
  },
  role_create: {
    type: 'role_create',
    label: 'Create Role',
    description: 'Deploy new permission unit.',
    category: 'moderation',
    icon: 'UserCog',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Role Name', type: 'text', required: true }],
  },
  channel_create: {
    type: 'channel_create',
    label: 'Create Channel',
    description: 'Deploy new text/voice unit.',
    category: 'advanced',
    icon: 'PlusCircle',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    properties: [{ key: 'name', label: 'Channel Name', type: 'text', required: true }],
  },
  member_timeout: {
    type: 'member_timeout',
    label: 'Restrict Member',
    description: 'Apply timeout window.',
    category: 'moderation',
    icon: 'Clock',
    color: '#f97316',
    inputs: 1,
    outputs: 1,
    properties: [
      { key: 'userId', label: 'User ID', type: 'text', required: true },
      { key: 'minutes', label: 'Duration', type: 'number', required: true },
    ],
  },
}

export const BLOCK_CATEGORIES: Record<BlockCategory, { label: string; description: string }> = {
  triggers: { label: 'Entry Points', description: 'Activation triggers' },
  logic: { label: 'Flow Logic', description: 'Control structures' },
  actions: { label: 'Responses', description: 'Guild interactions' },
  moderation: { label: 'Security', description: 'Server protection' },
  advanced: { label: 'Advanced', description: 'Niche integrations' },
  data: { label: 'Data', description: 'State and API' },
  // Stubs for internal compatibility
  replies: { label: 'Replies', description: 'Standard responses' },
  variables: { label: 'Variables', description: 'Internal storage' },
  conditions: { label: 'Checks', description: 'Data validation' },
}
