import type { BlockDefinition } from '@/types'

// ============================================================================
// Kyto - Complete Block Definitions
// Full Discord.js v14+ and Discord.py 2.0+ Support
// ============================================================================

export const BLOCK_DEFINITIONS: Record<string, BlockDefinition> = {
  // ============================================================================
  // TRIGGERS - Command Entry Points
  // ============================================================================

  command_slash: {
    type: 'command_slash',
    label: 'Slash Command',
    category: 'triggers',
    description: 'Triggers when a user runs a slash command',
    icon: 'Terminal',
    color: '#5865F2',
    inputs: 0,
    outputs: 1,
    tags: ['command', 'slash', 'interaction'],
    properties: [
      {
        key: 'name',
        label: 'Command Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., ping',
        helperText: 'Lowercase, no spaces, 1-32 characters',
        validation: {
          required: true,
          minLength: 1,
          maxLength: 32,
          pattern: '^[a-z0-9_-]+$',
        },
      },
      {
        key: 'description',
        label: 'Description',
        type: 'text',
        required: true,
        placeholder: 'e.g., Replies with Pong!',
        helperText: 'Shown in Discord command list',
        validation: {
          required: true,
          minLength: 1,
          maxLength: 100,
        },
      },
      {
        key: 'options',
        label: 'Command Options',
        type: 'options_list',
        required: false,
        defaultValue: [],
        helperText: 'Add parameters for your command',
      },
      {
        key: 'permissions',
        label: 'Required Permissions',
        type: 'multi_select',
        required: false,
        options: [
          { label: 'Administrator', value: 'Administrator' },
          { label: 'Manage Server', value: 'ManageGuild' },
          { label: 'Manage Channels', value: 'ManageChannels' },
          { label: 'Manage Roles', value: 'ManageRoles' },
          { label: 'Manage Messages', value: 'ManageMessages' },
          { label: 'Kick Members', value: 'KickMembers' },
          { label: 'Ban Members', value: 'BanMembers' },
          { label: 'Moderate Members', value: 'ModerateMembers' },
          { label: 'Manage Webhooks', value: 'ManageWebhooks' },
          { label: 'Manage Emojis', value: 'ManageEmojisAndStickers' },
          { label: 'Mention Everyone', value: 'MentionEveryone' },
        ],
        helperText: 'Users need these permissions to use the command',
      },
      {
        key: 'dmPermission',
        label: 'Allow in DMs',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helperText: 'Can be used in direct messages',
      },
      {
        key: 'nsfw',
        label: 'NSFW Only',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helperText: 'Only available in age-restricted channels',
      },
      {
        key: 'cooldown',
        label: 'Cooldown (seconds)',
        type: 'number',
        required: false,
        defaultValue: 0,
        helperText: 'Time between uses per user',
        validation: { min: 0, max: 86400 },
      },
    ],
  },

  command_subcommand: {
    type: 'command_subcommand',
    label: 'Subcommand',
    category: 'triggers',
    description: 'A subcommand within a slash command',
    icon: 'GitBranch',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Subcommand Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., add',
        validation: { required: true, maxLength: 32, pattern: '^[a-z0-9_-]+$' },
      },
      {
        key: 'description',
        label: 'Description',
        type: 'text',
        required: true,
        placeholder: 'e.g., Add a new item',
        validation: { required: true, maxLength: 100 },
      },
      {
        key: 'options',
        label: 'Options',
        type: 'options_list',
        required: false,
        defaultValue: [],
      },
    ],
  },

  command_subcommand_group: {
    type: 'command_subcommand_group',
    label: 'Subcommand Group',
    category: 'triggers',
    description: 'A group of related subcommands',
    icon: 'Folder',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Group Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., settings',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'text',
        required: true,
        placeholder: 'e.g., Server settings commands',
      },
    ],
  },

  context_menu_user: {
    type: 'context_menu_user',
    label: 'User Context Menu',
    category: 'triggers',
    description: 'Triggered when right-clicking a user',
    icon: 'User',
    color: '#5865F2',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Menu Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., Get User Info',
        validation: { required: true, maxLength: 32 },
      },
      {
        key: 'permissions',
        label: 'Required Permissions',
        type: 'multi_select',
        required: false,
        options: [
          { label: 'Administrator', value: 'Administrator' },
          { label: 'Manage Server', value: 'ManageGuild' },
          { label: 'Moderate Members', value: 'ModerateMembers' },
        ],
      },
    ],
  },

  context_menu_message: {
    type: 'context_menu_message',
    label: 'Message Context Menu',
    category: 'triggers',
    description: 'Triggered when right-clicking a message',
    icon: 'MessageSquare',
    color: '#5865F2',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Menu Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., Translate Message',
        validation: { required: true, maxLength: 32 },
      },
      {
        key: 'permissions',
        label: 'Required Permissions',
        type: 'multi_select',
        required: false,
        options: [
          { label: 'Administrator', value: 'Administrator' },
          { label: 'Manage Messages', value: 'ManageMessages' },
        ],
      },
    ],
  },

  autocomplete_handler: {
    type: 'autocomplete_handler',
    label: 'Autocomplete Handler',
    category: 'triggers',
    description: 'Handle autocomplete for command options',
    icon: 'Search',
    color: '#5865F2',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'commandName',
        label: 'Command Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., search',
      },
      {
        key: 'optionName',
        label: 'Option Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., query',
      },
    ],
  },

  prefix_command: {
    type: 'prefix_command',
    label: 'Prefix Command',
    category: 'triggers',
    description: 'Traditional prefix-based command (e.g., !help)',
    icon: 'Hash',
    color: '#747F8D',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Command Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., help',
      },
      {
        key: 'aliases',
        label: 'Aliases',
        type: 'array',
        required: false,
        placeholder: 'e.g., h, commands',
        helperText: 'Alternative names for this command',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'text',
        required: false,
        placeholder: 'e.g., Shows help information',
      },
    ],
  },

  check_permissions: {
    type: 'check_permissions',
    label: 'Check Permissions',
    category: 'logic',
    description: 'Check if user has specific permissions',
    icon: 'Shield',
    color: '#ED4245',
    inputs: 1,
    outputs: 2, // True/False paths
    properties: [
      {
        key: 'permission',
        label: 'Permission',
        type: 'select',
        required: true,
        options: [
          { label: 'Administrator', value: 'Administrator' },
          { label: 'Manage Server', value: 'ManageGuild' },
          { label: 'Manage Messages', value: 'ManageMessages' },
          { label: 'Kick Members', value: 'KickMembers' },
          { label: 'Ban Members', value: 'BanMembers' },
        ],
      },
      {
        key: 'errorReply',
        label: 'Error Reply',
        type: 'text',
        required: false,
        placeholder: 'You do not have permission!',
      },
    ],
  },

  // ============================================================================
  // EVENTS - Discord Gateway Events
  // ============================================================================

  event_listener: {
    type: 'event_listener',
    label: 'Event Listener',
    category: 'triggers',
    description: 'Listen for specific Discord events',
    icon: 'Zap',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'event',
        label: 'Event Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Message Created', value: 'messageCreate' },
          { label: 'Message Updated', value: 'messageUpdate' },
          { label: 'Message Deleted', value: 'messageDelete' },
          { label: 'Message Bulk Delete', value: 'messageDeleteBulk' },
          { label: 'Member Joined', value: 'guildMemberAdd' },
          { label: 'Member Left', value: 'guildMemberRemove' },
          { label: 'Member Updated', value: 'guildMemberUpdate' },
          { label: 'Role Created', value: 'roleCreate' },
          { label: 'Role Updated', value: 'roleUpdate' },
          { label: 'Role Deleted', value: 'roleDelete' },
          { label: 'Channel Created', value: 'channelCreate' },
          { label: 'Channel Updated', value: 'channelUpdate' },
          { label: 'Channel Deleted', value: 'channelDelete' },
          { label: 'Thread Created', value: 'threadCreate' },
          { label: 'Thread Updated', value: 'threadUpdate' },
          { label: 'Thread Deleted', value: 'threadDelete' },
          { label: 'Thread Member Update', value: 'threadMembersUpdate' },
          { label: 'Reaction Added', value: 'messageReactionAdd' },
          { label: 'Reaction Removed', value: 'messageReactionRemove' },
          { label: 'Reaction Removed All', value: 'messageReactionRemoveAll' },
          { label: 'Reaction Removed Emoji', value: 'messageReactionRemoveEmoji' },
          { label: 'Interaction Created', value: 'interactionCreate' },
          { label: 'Voice State Update', value: 'voiceStateUpdate' },
          { label: 'Presence Update', value: 'presenceUpdate' },
          { label: 'Typing Start', value: 'typingStart' },
          { label: 'Invite Created', value: 'inviteCreate' },
          { label: 'Invite Deleted', value: 'inviteDelete' },
          { label: 'Guild Ban Added', value: 'guildBanAdd' },
          { label: 'Guild Ban Removed', value: 'guildBanRemove' },
          { label: 'Guild Update', value: 'guildUpdate' },
          { label: 'Scheduled Event Created', value: 'guildScheduledEventCreate' },
          { label: 'Scheduled Event Updated', value: 'guildScheduledEventUpdate' },
          { label: 'Scheduled Event Deleted', value: 'guildScheduledEventDelete' },
          { label: 'Scheduled Event User Add', value: 'guildScheduledEventUserAdd' },
          { label: 'Scheduled Event User Remove', value: 'guildScheduledEventUserRemove' },
          { label: 'AutoMod Action Execution', value: 'autoModerationActionExecution' },
          { label: 'AutoMod Rule Create', value: 'autoModerationRuleCreate' },
          { label: 'AutoMod Rule Update', value: 'autoModerationRuleUpdate' },
          { label: 'AutoMod Rule Delete', value: 'autoModerationRuleDelete' },
          { label: 'Stage Instance Create', value: 'stageInstanceCreate' },
          { label: 'Stage Instance Update', value: 'stageInstanceUpdate' },
          { label: 'Stage Instance Delete', value: 'stageInstanceDelete' },
          { label: 'Sticker Create', value: 'stickerCreate' },
          { label: 'Sticker Update', value: 'stickerUpdate' },
          { label: 'Sticker Delete', value: 'stickerDelete' },
          { label: 'Emoji Create', value: 'emojiCreate' },
          { label: 'Emoji Update', value: 'emojiUpdate' },
          { label: 'Emoji Delete', value: 'emojiDelete' },
          { label: 'Webhook Update', value: 'webhookUpdate' },
          { label: 'Guild Integraions Update', value: 'guildIntegrationsUpdate' },
          { label: 'Integration Create', value: 'integrationCreate' },
          { label: 'Integration Update', value: 'integrationUpdate' },
          { label: 'Integration Delete', value: 'integrationDelete' },
          { label: 'Guild Available', value: 'guildAvailable' },
          { label: 'Guild Unavailable', value: 'guildUnavailable' },
          { label: 'Guild Members Chunk', value: 'guildMembersChunk' },
          { label: 'Guild Member Available', value: 'guildMemberAvailable' },
          { label: 'Guild Member Speaking', value: 'guildMemberSpeaking' },
          { label: 'Debug', value: 'debug' },
          { label: 'Error', value: 'error' },
          { label: 'Warn', value: 'warn' },
          { label: 'Shard Disconnect', value: 'shardDisconnect' },
          { label: 'Shard Error', value: 'shardError' },
          { label: 'Shard Ready', value: 'shardReady' },
          { label: 'Shard Reconnecting', value: 'shardReconnecting' },
          { label: 'Shard Resume', value: 'shardResume' },
          { label: 'Invalidated', value: 'invalidated' },
          { label: 'Raw', value: 'raw' },
          { label: 'Bot Ready', value: 'ready' },
          { label: 'Bot Reconnecting', value: 'reconnecting' },
          { label: 'Rate Limit', value: 'rateLimit' },
        ],
      },
    ],
  },

  event_ready: {
    type: 'event_ready',
    label: 'Bot Ready',
    category: 'events',
    description: 'Fires when the bot successfully connects',
    icon: 'Power',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'once',
        label: 'Run Once',
        type: 'boolean',
        required: false,
        defaultValue: true,
        helperText: 'Only trigger once on first ready',
      },
    ],
  },

  event_message_create: {
    type: 'event_message_create',
    label: 'Message Created',
    category: 'events',
    description: 'Fires when a new message is sent',
    icon: 'MessageCircle',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'ignoreBots',
        label: 'Ignore Bots',
        type: 'boolean',
        required: false,
        defaultValue: true,
        helperText: 'Skip messages from other bots',
      },
      {
        key: 'channelFilter',
        label: 'Channel Filter',
        type: 'channel_select',
        required: false,
        helperText: 'Only trigger in specific channels',
      },
      {
        key: 'contentFilter',
        label: 'Content Filter',
        type: 'text',
        required: false,
        placeholder: 'e.g., hello or regex: /^!/',
        helperText: 'Filter by message content',
      },
    ],
  },

  event_message_update: {
    type: 'event_message_update',
    label: 'Message Edited',
    category: 'events',
    description: 'Fires when a message is edited',
    icon: 'Edit',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'ignoreBots',
        label: 'Ignore Bots',
        type: 'boolean',
        required: false,
        defaultValue: true,
      },
    ],
  },

  event_message_delete: {
    type: 'event_message_delete',
    label: 'Message Deleted',
    category: 'events',
    description: 'Fires when a message is deleted',
    icon: 'Trash2',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_message_bulk_delete: {
    type: 'event_message_bulk_delete',
    label: 'Messages Bulk Deleted',
    category: 'events',
    description: 'Fires when multiple messages are deleted at once',
    icon: 'Trash',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_member_join: {
    type: 'event_member_join',
    label: 'Member Joined',
    category: 'events',
    description: 'Fires when a new member joins the server',
    icon: 'UserPlus',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_member_leave: {
    type: 'event_member_leave',
    label: 'Member Left',
    category: 'events',
    description: 'Fires when a member leaves the server',
    icon: 'UserMinus',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_member_update: {
    type: 'event_member_update',
    label: 'Member Updated',
    category: 'events',
    description: 'Fires when member roles/nickname change',
    icon: 'UserCog',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_guild_ban_add: {
    type: 'event_guild_ban_add',
    label: 'Member Banned',
    category: 'events',
    description: 'Fires when a user is banned',
    icon: 'Gavel',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_guild_ban_remove: {
    type: 'event_guild_ban_remove',
    label: 'Member Unbanned',
    category: 'events',
    description: 'Fires when a user is unbanned',
    icon: 'Scale',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_role_create: {
    type: 'event_role_create',
    label: 'Role Created',
    category: 'events',
    description: 'Fires when a new role is created',
    icon: 'Shield',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_role_update: {
    type: 'event_role_update',
    label: 'Role Updated',
    category: 'events',
    description: 'Fires when a role is modified',
    icon: 'ShieldCheck',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_role_delete: {
    type: 'event_role_delete',
    label: 'Role Deleted',
    category: 'events',
    description: 'Fires when a role is deleted',
    icon: 'ShieldOff',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_channel_create: {
    type: 'event_channel_create',
    label: 'Channel Created',
    category: 'events',
    description: 'Fires when a new channel is created',
    icon: 'Hash',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_channel_update: {
    type: 'event_channel_update',
    label: 'Channel Updated',
    category: 'events',
    description: 'Fires when a channel is modified',
    icon: 'Settings',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_channel_delete: {
    type: 'event_channel_delete',
    label: 'Channel Deleted',
    category: 'events',
    description: 'Fires when a channel is deleted',
    icon: 'Trash',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_thread_create: {
    type: 'event_thread_create',
    label: 'Thread Created',
    category: 'events',
    description: 'Fires when a new thread is created',
    icon: 'MessageSquarePlus',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_thread_update: {
    type: 'event_thread_update',
    label: 'Thread Updated',
    category: 'events',
    description: 'Fires when a thread is modified',
    icon: 'MessageSquare',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_thread_delete: {
    type: 'event_thread_delete',
    label: 'Thread Deleted',
    category: 'events',
    description: 'Fires when a thread is deleted',
    icon: 'MessageSquareX',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_message_reaction_add: {
    type: 'event_message_reaction_add',
    label: 'Reaction Added',
    category: 'events',
    description: 'Fires when a reaction is added',
    icon: 'Smile',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'emojiFilter',
        label: 'Emoji Filter',
        type: 'text',
        required: false,
        placeholder: 'e.g., 👍 or :thumbsup:',
        helperText: 'Only trigger for specific emojis',
      },
    ],
  },

  event_message_reaction_remove: {
    type: 'event_message_reaction_remove',
    label: 'Reaction Removed',
    category: 'events',
    description: 'Fires when a reaction is removed',
    icon: 'Frown',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_interaction_create: {
    type: 'event_interaction_create',
    label: 'Interaction Created',
    category: 'events',
    description: 'Fires for any interaction (buttons, menus, etc.)',
    icon: 'MousePointer',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'type',
        label: 'Interaction Type',
        type: 'select',
        required: false,
        options: [
          { label: 'All', value: 'all' },
          { label: 'Button', value: 'button' },
          { label: 'Select Menu', value: 'selectMenu' },
          { label: 'Modal Submit', value: 'modalSubmit' },
          { label: 'Autocomplete', value: 'autocomplete' },
        ],
        defaultValue: 'all',
      },
    ],
  },

  on_button_click: {
    type: 'on_button_click',
    label: 'Button Clicked',
    category: 'events',
    description: 'Fires when a specific button is clicked',
    icon: 'MousePointer',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Button ID',
        type: 'text',
        required: true,
        placeholder: 'e.g., btn_confirm',
        helperText: 'The custom ID of the button',
      },
      {
        key: 'matchType',
        label: 'Match Type',
        type: 'select',
        required: false,
        options: [
          { label: 'Exact Match', value: 'exact' },
          { label: 'Starts With', value: 'startsWith' },
          { label: 'Contains', value: 'contains' },
          { label: 'Regex', value: 'regex' },
        ],
        defaultValue: 'exact',
      },
    ],
  },

  on_select_menu: {
    type: 'on_select_menu',
    label: 'Select Menu Used',
    category: 'events',
    description: 'Fires when a specific select menu is used',
    icon: 'List',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Menu ID',
        type: 'text',
        required: true,
        placeholder: 'e.g., menu_roles',
      },
      {
        key: 'matchType',
        label: 'Match Type',
        type: 'select',
        required: false,
        options: [
          { label: 'Exact Match', value: 'exact' },
          { label: 'Starts With', value: 'startsWith' },
          { label: 'Regex', value: 'regex' },
        ],
        defaultValue: 'exact',
      },
    ],
  },

  on_modal_submit: {
    type: 'on_modal_submit',
    label: 'Modal Submitted',
    category: 'events',
    description: 'Fires when a specific modal is submitted',
    icon: 'FileText',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Modal ID',
        type: 'text',
        required: true,
        placeholder: 'e.g., modal_feedback',
      },
    ],
  },

  event_voice_state_update: {
    type: 'event_voice_state_update',
    label: 'Voice State Changed',
    category: 'events',
    description: 'Fires when someone joins/leaves/moves in voice',
    icon: 'Mic',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [
      {
        key: 'action',
        label: 'Action Filter',
        type: 'select',
        required: false,
        options: [
          { label: 'Any', value: 'any' },
          { label: 'Join', value: 'join' },
          { label: 'Leave', value: 'leave' },
          { label: 'Move', value: 'move' },
          { label: 'Mute/Unmute', value: 'mute' },
          { label: 'Deafen/Undeafen', value: 'deafen' },
        ],
        defaultValue: 'any',
      },
    ],
  },

  event_presence_update: {
    type: 'event_presence_update',
    label: 'Presence Updated',
    category: 'events',
    description: 'Fires when user status/activity changes',
    icon: 'Activity',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_typing_start: {
    type: 'event_typing_start',
    label: 'Typing Started',
    category: 'events',
    description: 'Fires when someone starts typing',
    icon: 'Type',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_invite_create: {
    type: 'event_invite_create',
    label: 'Invite Created',
    category: 'events',
    description: 'Fires when a new invite is created',
    icon: 'Link',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_invite_delete: {
    type: 'event_invite_delete',
    label: 'Invite Deleted',
    category: 'events',
    description: 'Fires when an invite is deleted/expires',
    icon: 'LinkOff',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_guild_update: {
    type: 'event_guild_update',
    label: 'Server Updated',
    category: 'events',
    description: 'Fires when server settings change',
    icon: 'Server',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_scheduled_event_create: {
    type: 'event_scheduled_event_create',
    label: 'Event Scheduled',
    category: 'events',
    description: 'Fires when a scheduled event is created',
    icon: 'Calendar',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_automod_action_execution: {
    type: 'event_automod_action_execution',
    label: 'AutoMod Triggered',
    category: 'events',
    description: 'Fires when AutoMod takes action',
    icon: 'ShieldAlert',
    color: '#57F287',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  event_error: {
    type: 'event_error',
    label: 'Error Occurred',
    category: 'events',
    description: 'Fires when the client encounters an error',
    icon: 'AlertTriangle',
    color: '#ED4245',
    inputs: 0,
    outputs: 1,
    properties: [],
  },

  // ============================================================================
  // ACTIONS - Replies & Interactions
  // ============================================================================

  action_reply: {
    type: 'action_reply',
    label: 'Reply to Interaction',
    category: 'actions',
    description: 'Send a reply to a slash command or interaction',
    icon: 'Reply',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'useEmbed',
        label: 'Use Embed',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helperText: 'Send as a rich embed instead of plain text',
      },
      {
        key: 'content',
        label: 'Message Content',
        type: 'textarea',
        required: false,
        placeholder: 'Hello, {user.username}!',
        helperText: 'Use variables like {user.username}, {server.name}',
        showIf: (props: Record<string, any>) => !props.useEmbed,
      },
      {
        key: 'embed_title',
        label: 'Embed Title',
        type: 'text',
        required: false,
        showIf: (props: Record<string, any>) => props.useEmbed,
      },
      {
        key: 'embed_description',
        label: 'Embed Description',
        type: 'textarea',
        required: false,
        showIf: (props: Record<string, any>) => props.useEmbed,
      },
      {
        key: 'embed_color',
        label: 'Embed Color',
        type: 'color',
        required: false,
        defaultValue: '#5865F2',
        showIf: (props: Record<string, any>) => props.useEmbed,
      },
      {
        key: 'ephemeral',
        label: 'Ephemeral (Hidden)',
        type: 'boolean',
        required: false,
        defaultValue: false,
        helperText: 'Only visible to the user who triggered',
      },
      {
        key: 'tts',
        label: 'Text-to-Speech',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  action_defer_reply: {
    type: 'action_defer_reply',
    label: 'Defer Reply',
    category: 'actions',
    description: 'Show "Bot is thinking..." while processing',
    icon: 'Loader',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'ephemeral',
        label: 'Ephemeral',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  action_edit_reply: {
    type: 'action_edit_reply',
    label: 'Edit Reply',
    category: 'actions',
    description: 'Edit the initial reply',
    icon: 'Edit',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'content',
        label: 'New Content',
        type: 'textarea',
        required: false,
        placeholder: 'Updated message content',
      },
    ],
  },

  action_follow_up: {
    type: 'action_follow_up',
    label: 'Follow Up',
    category: 'actions',
    description: 'Send an additional message after the reply',
    icon: 'CornerDownRight',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'content',
        label: 'Content',
        type: 'textarea',
        required: false,
      },
      {
        key: 'ephemeral',
        label: 'Ephemeral',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  action_defer_update: {
    type: 'action_defer_update',
    label: 'Defer Update',
    category: 'actions',
    description: 'Acknowledge component interaction without updating',
    icon: 'CheckCircle',
    color: '#5865F2',
    inputs: 1,
    outputs: 1,
    properties: [],
  },

  // ============================================================================
  // ACTIONS - Messages
  // ============================================================================

  send_message: {
    type: 'send_message',
    label: 'Send Message',
    category: 'messages',
    description: 'Send a message to a specific channel',
    icon: 'Send',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channelId',
        label: 'Channel',
        type: 'channel_select',
        required: true,
        placeholder: 'Select channel or enter ID',
        helperText: 'Use {channel.id} for current channel',
      },
      {
        key: 'useEmbed',
        label: 'Use Embed',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
      {
        key: 'content',
        label: 'Content',
        type: 'textarea',
        required: false,
        placeholder: 'Message content...',
        showIf: (props: Record<string, any>) => !props.useEmbed,
      },
      {
        key: 'embed_title',
        label: 'Embed Title',
        type: 'text',
        showIf: (props: Record<string, any>) => props.useEmbed,
      },
      {
        key: 'embed_description',
        label: 'Embed Description',
        type: 'textarea',
        showIf: (props: Record<string, any>) => props.useEmbed,
      },
      {
        key: 'tts',
        label: 'Text-to-Speech',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  send_embed: {
    type: 'send_embed',
    label: 'Send Embed',
    category: 'embeds',
    description: 'Send a rich embed message',
    icon: 'Layout',
    color: '#E91E63',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channelId',
        label: 'Channel',
        type: 'channel_select',
        required: true,
        placeholder: 'Select channel or enter ID',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'text',
        required: false,
        placeholder: 'Embed title',
        validation: { maxLength: 256 },
      },
      {
        key: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        placeholder: 'Embed description',
        validation: { maxLength: 4096 },
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        required: false,
        defaultValue: '#5865F2',
        helperText: 'Hex color code',
      },
      {
        key: 'url',
        label: 'URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com',
      },
      {
        key: 'timestamp',
        label: 'Show Timestamp',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
      {
        key: 'image',
        label: 'Image URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/image.png',
      },
      {
        key: 'thumbnail',
        label: 'Thumbnail URL',
        type: 'url',
        required: false,
      },
      {
        key: 'authorName',
        label: 'Author Name',
        type: 'text',
        required: false,
        validation: { maxLength: 256 },
      },
      {
        key: 'authorIcon',
        label: 'Author Icon URL',
        type: 'url',
        required: false,
      },
      {
        key: 'footerText',
        label: 'Footer Text',
        type: 'text',
        required: false,
        validation: { maxLength: 2048 },
      },
      {
        key: 'footerIcon',
        label: 'Footer Icon URL',
        type: 'url',
        required: false,
      },
    ],
  },

  edit_message: {
    type: 'edit_message',
    label: 'Edit Message',
    category: 'messages',
    description: 'Edit an existing message',
    icon: 'Edit3',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
        placeholder: 'ID of message to edit',
      },
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'channel_select',
        required: true,
      },
      {
        key: 'newContent',
        label: 'New Content',
        type: 'textarea',
        required: false,
      },
    ],
  },

  delete_message: {
    type: 'delete_message',
    label: 'Delete Message',
    category: 'messages',
    description: 'Delete a message',
    icon: 'Trash2',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
      },
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'channel_select',
        required: false,
        helperText: 'Optional if message is in context',
      },
    ],
  },

  add_reaction: {
    type: 'add_reaction',
    label: 'Add Reaction',
    category: 'messages',
    description: 'React to a message',
    icon: 'Smile',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
      },
      {
        key: 'emoji',
        label: 'Emoji',
        type: 'emoji_select',
        required: true,
        placeholder: '👍 or :thumbsup: or emoji ID',
      },
    ],
  },

  pin_message: {
    type: 'pin_message',
    label: 'Pin Message',
    category: 'messages',
    description: 'Pin a message to the channel',
    icon: 'Pin',
    color: '#3B82F6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
      },
    ],
  },

  // ============================================================================
  // COMPONENTS - Buttons, Menus, Modals
  // ============================================================================

  add_button: {
    type: 'add_button',
    label: 'Add Button',
    category: 'components',
    description: 'Add an interactive button',
    icon: 'MousePointer',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'label',
        label: 'Button Label',
        type: 'text',
        required: true,
        placeholder: 'Click Me!',
        validation: { maxLength: 80 },
      },
      {
        key: 'customId',
        label: 'Custom ID',
        type: 'text',
        required: true,
        placeholder: 'btn_confirm',
        helperText: 'Unique identifier for this button',
        validation: { maxLength: 100 },
      },
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        required: true,
        defaultValue: 'Primary',
        options: [
          { label: 'Primary (Blurple)', value: 'Primary' },
          { label: 'Secondary (Gray)', value: 'Secondary' },
          { label: 'Success (Green)', value: 'Success' },
          { label: 'Danger (Red)', value: 'Danger' },
        ],
      },
      {
        key: 'emoji',
        label: 'Emoji',
        type: 'emoji_select',
        required: false,
        placeholder: '⚡',
      },
      {
        key: 'disabled',
        label: 'Disabled',
        type: 'boolean',
        required: false,
        defaultValue: false,
      },
    ],
  },

  add_link_button: {
    type: 'add_link_button',
    label: 'Add Link Button',
    category: 'components',
    description: 'Add a button that opens a URL',
    icon: 'Link',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'label',
        label: 'Button Label',
        type: 'text',
        required: true,
        validation: { maxLength: 80 },
      },
      {
        key: 'url',
        label: 'URL',
        type: 'url',
        required: true,
        placeholder: 'https://example.com',
      },
      {
        key: 'emoji',
        label: 'Emoji',
        type: 'emoji_select',
        required: false,
      },
    ],
  },

  add_select_menu: {
    type: 'add_select_menu',
    label: 'Add Select Menu',
    category: 'components',
    description: 'Add a dropdown select menu',
    icon: 'List',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Custom ID',
        type: 'text',
        required: true,
        placeholder: 'select_role',
        validation: { maxLength: 100 },
      },
      {
        key: 'placeholder',
        label: 'Placeholder',
        type: 'text',
        required: false,
        placeholder: 'Choose an option...',
        validation: { maxLength: 150 },
      },
      {
        key: 'minValues',
        label: 'Min Values',
        type: 'number',
        required: false,
        defaultValue: 1,
        validation: { min: 0, max: 25 },
      },
      {
        key: 'maxValues',
        label: 'Max Values',
        type: 'number',
        required: false,
        defaultValue: 1,
        validation: { min: 1, max: 25 },
      },
      {
        key: 'options',
        label: 'Options',
        type: 'options_list',
        required: true,
        helperText: 'Add options for the menu',
      },
    ],
  },

  add_role_select: {
    type: 'add_role_select',
    label: 'Add Role Select',
    category: 'components',
    description: 'Select menu for choosing roles',
    icon: 'Shield',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Custom ID',
        type: 'text',
        required: true,
        placeholder: 'select_role',
      },
      {
        key: 'placeholder',
        label: 'Placeholder',
        type: 'text',
        required: false,
        placeholder: 'Select a role...',
      },
      {
        key: 'minValues',
        label: 'Min Selections',
        type: 'number',
        defaultValue: 1,
        validation: { min: 0, max: 25 },
      },
      {
        key: 'maxValues',
        label: 'Max Selections',
        type: 'number',
        defaultValue: 1,
        validation: { min: 1, max: 25 },
      },
    ],
  },

  show_modal: {
    type: 'show_modal',
    label: 'Show Modal',
    category: 'components',
    description: 'Display a popup form',
    icon: 'FileText',
    color: '#F472B6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'customId',
        label: 'Custom ID',
        type: 'text',
        required: true,
        placeholder: 'modal_feedback',
        validation: { maxLength: 100 },
      },
      {
        key: 'title',
        label: 'Modal Title',
        type: 'text',
        required: true,
        placeholder: 'Feedback Form',
        validation: { maxLength: 45 },
      },
      {
        key: 'inputs',
        label: 'Text Inputs',
        type: 'options_list',
        required: true,
        helperText: 'Add text input fields (max 5)',
      },
    ],
  },

  // ============================================================================
  // MODERATION
  // ============================================================================

  action_ban: {
    type: 'action_ban',
    label: 'Ban Member',
    category: 'moderation',
    description: 'Ban a user from the server',
    icon: 'Gavel',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'userId',
        label: 'User',
        type: 'user_select',
        required: true,
        placeholder: 'User ID or mention',
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'text',
        required: false,
        placeholder: 'Rule violation',
        validation: { maxLength: 512 },
      },
      {
        key: 'deleteMessageDays',
        label: 'Delete Message History',
        type: 'number',
        required: false,
        defaultValue: 0,
        helperText: 'Delete messages from last X days (0-7)',
        validation: { min: 0, max: 7 },
      },
    ],
  },

  action_kick: {
    type: 'action_kick',
    label: 'Kick Member',
    category: 'moderation',
    description: 'Kick a user from the server',
    icon: 'UserMinus',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'userId',
        label: 'User',
        type: 'user_select',
        required: true,
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'text',
        required: false,
        validation: { maxLength: 512 },
      },
    ],
  },

  action_timeout: {
    type: 'action_timeout',
    label: 'Timeout Member',
    category: 'moderation',
    description: 'Timeout a member for a duration',
    icon: 'Clock',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'userId',
        label: 'User',
        type: 'user_select',
        required: true,
      },
      {
        key: 'duration',
        label: 'Duration (minutes)',
        type: 'number',
        required: true,
        defaultValue: 60,
        helperText: 'Max 40320 (28 days)',
        validation: { min: 1, max: 40320 },
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'text',
        required: false,
      },
    ],
  },

  action_purge: {
    type: 'action_purge',
    label: 'Purge Messages',
    category: 'moderation',
    description: 'Bulk delete messages',
    icon: 'Trash',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'amount',
        label: 'Amount',
        type: 'number',
        required: true,
        defaultValue: 10,
        helperText: 'Number of messages (1-100)',
        validation: { min: 1, max: 100 },
      },
      {
        key: 'filter',
        label: 'Filter',
        type: 'select',
        required: false,
        defaultValue: 'all',
        options: [
          { label: 'All Messages', value: 'all' },
          { label: 'Bots Only', value: 'bots' },
          { label: 'Users Only', value: 'users' },
          { label: 'Contains Text', value: 'contains' },
        ],
      },
      {
        key: 'filterValue',
        label: 'Filter Value',
        type: 'text',
        required: false,
        placeholder: 'Text to filter by',
        showIf: (props: Record<string, any>) => props.filter === 'contains',
      },
    ],
  },

  action_role_add: {
    type: 'action_role_add',
    label: 'Add Role',
    category: 'roles',
    description: 'Give a role to a member',
    icon: 'ShieldPlus',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'userId',
        label: 'User',
        type: 'user_select',
        required: true,
      },
      {
        key: 'roleId',
        label: 'Role',
        type: 'role_select',
        required: true,
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'text',
        required: false,
      },
    ],
  },

  action_role_remove: {
    type: 'action_role_remove',
    label: 'Remove Role',
    category: 'roles',
    description: 'Remove a role from a member',
    icon: 'ShieldMinus',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'userId',
        label: 'User',
        type: 'user_select',
        required: true,
      },
      {
        key: 'roleId',
        label: 'Role',
        type: 'role_select',
        required: true,
      },
      {
        key: 'reason',
        label: 'Reason',
        type: 'text',
        required: false,
      },
    ],
  },

  error_handler: {
    type: 'error_handler',
    label: 'Error Handler',
    category: 'logic',
    description: 'Catches and handles errors from previous blocks',
    icon: 'AlertTriangle',
    color: '#ED4245',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'logToConsole',
        label: 'Log to Console',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },

  // ============================================================================
  // LOGIC & CONTROL FLOW
  // ============================================================================

  if_condition: {
    type: 'if_condition',
    label: 'If Condition',
    category: 'logic',
    description: 'Branch based on a condition',
    icon: 'GitBranch',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 2,
    properties: [
      {
        key: 'leftValue',
        label: 'Left Value',
        type: 'text',
        required: true,
        placeholder: 'e.g., {user.id}',
      },
      {
        key: 'operator',
        label: 'Operator',
        type: 'select',
        required: true,
        defaultValue: 'equals',
        options: [
          { label: 'Equals (==)', value: 'equals' },
          { label: 'Not Equals (!=)', value: 'notEquals' },
          { label: 'Greater Than (>)', value: 'greaterThan' },
          { label: 'Less Than (<)', value: 'lessThan' },
          { label: 'Greater or Equal (>=)', value: 'greaterOrEqual' },
          { label: 'Less or Equal (<=)', value: 'lessOrEqual' },
          { label: 'Contains', value: 'contains' },
          { label: 'Starts With', value: 'startsWith' },
          { label: 'Ends With', value: 'endsWith' },
          { label: 'Matches Regex', value: 'regex' },
        ],
      },
      {
        key: 'rightValue',
        label: 'Right Value',
        type: 'text',
        required: true,
        placeholder: 'Value to compare',
      },
    ],
    handles: {
      inputs: [{ id: 'in', label: 'Input', type: 'default' }],
      outputs: [
        { id: 'true', label: 'True', type: 'success' },
        { id: 'false', label: 'False', type: 'error' },
      ],
    },
  },

  for_loop: {
    type: 'for_loop',
    label: 'For Loop',
    category: 'logic',
    description: 'Repeat actions a specific number of times',
    icon: 'Repeat',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 2,
    properties: [
      {
        key: 'times',
        label: 'Iterations',
        type: 'number',
        required: true,
        defaultValue: 5,
        placeholder: 'Number of times to loop',
        validation: { min: 1, max: 1000 },
      },
      {
        key: 'variableName',
        label: 'Index Variable',
        type: 'text',
        required: false,
        defaultValue: 'i',
        placeholder: 'Variable name for counter',
      },
    ],
    handles: {
      outputs: [
        { id: 'loop', label: 'Loop Body', type: 'loop' },
        { id: 'complete', label: 'Complete', type: 'default' },
      ],
    },
  },

  wait: {
    type: 'wait',
    label: 'Wait',
    category: 'logic',
    description: 'Pause execution for a duration',
    icon: 'Clock',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'duration',
        label: 'Duration (ms)',
        type: 'number',
        required: true,
        defaultValue: 1000,
        placeholder: 'Milliseconds',
        helperText: '1000ms = 1 second',
        validation: { min: 0, max: 600000 },
      },
    ],
  },

  try_catch: {
    type: 'try_catch',
    label: 'Try/Catch',
    category: 'logic',
    description: 'Handle errors gracefully',
    icon: 'AlertTriangle',
    color: '#EF4444',
    inputs: 1,
    outputs: 2,
    properties: [
      {
        key: 'errorVariable',
        label: 'Error Variable Name',
        type: 'text',
        required: false,
        defaultValue: 'error',
        placeholder: 'Variable to store error',
      },
    ],
    handles: {
      outputs: [
        { id: 'try', label: 'Try', type: 'default' },
        { id: 'catch', label: 'Catch Error', type: 'error' },
      ],
    },
  },

  random_number: {
    type: 'random_number',
    label: 'Random Number',
    category: 'logic',
    description: 'Generate a random number',
    icon: 'Shuffle',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'min',
        label: 'Minimum',
        type: 'number',
        required: true,
        defaultValue: 1,
      },
      {
        key: 'max',
        label: 'Maximum',
        type: 'number',
        required: true,
        defaultValue: 100,
      },
      {
        key: 'variableName',
        label: 'Store In Variable',
        type: 'text',
        required: false,
        placeholder: 'randomNum',
      },
    ],
  },

  // ============================================================================
  // VARIABLES & DATA
  // ============================================================================

  set_variable: {
    type: 'set_variable',
    label: 'Set Variable',
    category: 'variables',
    description: 'Store a value in a variable',
    icon: 'Save',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Variable Name',
        type: 'text',
        required: true,
        placeholder: 'myVariable',
        validation: { pattern: '^[a-zA-Z_][a-zA-Z0-9_]*$' },
      },
      {
        key: 'value',
        label: 'Value',
        type: 'text',
        required: true,
        placeholder: 'Value to store',
      },
      {
        key: 'scope',
        label: 'Scope',
        type: 'select',
        required: false,
        defaultValue: 'local',
        options: [
          { label: 'Local (Command)', value: 'local' },
          { label: 'Global (Bot)', value: 'global' },
          { label: 'User', value: 'user' },
          { label: 'Server', value: 'server' },
        ],
      },
    ],
  },

  get_variable: {
    type: 'get_variable',
    label: 'Get Variable',
    category: 'variables',
    description: 'Retrieve a stored variable',
    icon: 'Download',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'name',
        label: 'Variable Name',
        type: 'variable_select',
        required: true,
        placeholder: 'myVariable',
      },
      {
        key: 'defaultValue',
        label: 'Default Value',
        type: 'text',
        required: false,
        placeholder: 'Value if not found',
      },
    ],
  },

  // ============================================================================
  // HTTP & API
  // ============================================================================

  http_request: {
    type: 'http_request',
    label: 'HTTP Request',
    category: 'api',
    description: 'Make an HTTP API request',
    icon: 'Globe',
    color: '#6366F1',
    inputs: 1,
    outputs: 2,
    properties: [
      {
        key: 'url',
        label: 'URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.example.com/data',
      },
      {
        key: 'method',
        label: 'Method',
        type: 'select',
        required: true,
        defaultValue: 'GET',
        options: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
          { label: 'PATCH', value: 'PATCH' },
          { label: 'DELETE', value: 'DELETE' },
        ],
      },
      {
        key: 'headers',
        label: 'Headers',
        type: 'key_value',
        required: false,
        placeholder: 'Authorization: Bearer token',
      },
      {
        key: 'body',
        label: 'Body',
        type: 'code',
        required: false,
        placeholder: '{"key": "value"}',
        showIf: (props: Record<string, any>) => ['POST', 'PUT', 'PATCH'].includes(props.method),
      },
      {
        key: 'responseVariable',
        label: 'Store Response In',
        type: 'text',
        required: false,
        placeholder: 'apiResponse',
      },
    ],
    handles: {
      outputs: [
        { id: 'success', label: 'Success', type: 'success' },
        { id: 'error', label: 'Error', type: 'error' },
      ],
    },
  },

  json_parse: {
    type: 'json_parse',
    label: 'Parse JSON',
    category: 'data',
    description: 'Parse JSON string to object',
    icon: 'Code',
    color: '#14B8A6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'jsonString',
        label: 'JSON String',
        type: 'textarea',
        required: true,
        placeholder: '{"name": "value"}',
      },
      {
        key: 'variableName',
        label: 'Store In Variable',
        type: 'text',
        required: false,
        placeholder: 'parsedData',
      },
    ],
  },

  console_log: {
    type: 'console_log',
    label: 'Console Log',
    category: 'debugging',
    description: 'Log a message to the console',
    icon: 'Terminal',
    color: '#6B7280',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'message',
        label: 'Message',
        type: 'text',
        required: true,
        placeholder: 'Debug message',
      },
      {
        key: 'level',
        label: 'Log Level',
        type: 'select',
        required: false,
        defaultValue: 'info',
        options: [
          { label: 'Info', value: 'info' },
          { label: 'Warn', value: 'warn' },
          { label: 'Error', value: 'error' },
          { label: 'Debug', value: 'debug' },
        ],
      },
    ],
  },

  call_module: {
    type: 'call_module',
    label: 'Call Module',
    category: 'advanced',
    description: 'Execute another module',
    icon: 'Layers',
    color: '#EC4899',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'moduleId',
        label: 'Module',
        type: 'module_select',
        required: true,
        placeholder: 'Select module',
      },
      {
        key: 'parameters',
        label: 'Parameters',
        type: 'key_value',
        required: false,
        helperText: 'Pass data to the module',
      },
    ],
  },

  // Additional Discord functionality blocks
  send_dm: {
    type: 'dm_member',
    label: 'Send DM',
    category: 'actions',
    description: 'Send a direct message to a user',
    icon: 'Mail',
    color: '#8B5CF6',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'userId',
        label: 'User ID',
        type: 'user_select',
        required: true,
        placeholder: 'Select user or enter ID',
      },
      {
        key: 'content',
        label: 'Message Content',
        type: 'textarea',
        required: true,
        placeholder: 'Enter your message...',
        validation: { maxLength: 2000 },
      },
    ],
  },

  edit_message: {
    type: 'edit_message',
    label: 'Edit Message',
    category: 'messages',
    description: 'Edit an existing message',
    icon: 'Edit3',
    color: '#F59E0B',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'channel_select',
        required: true,
        placeholder: 'Select channel or enter ID',
      },
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
        placeholder: 'Enter message ID',
      },
      {
        key: 'content',
        label: 'New Content',
        type: 'textarea',
        required: false,
        placeholder: 'New message content',
        validation: { maxLength: 2000 },
      },
    ],
  },

  delete_message: {
    type: 'delete_message',
    label: 'Delete Message',
    category: 'messages',
    description: 'Delete a message from a channel',
    icon: 'Trash2',
    color: '#EF4444',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'channel_select',
        required: true,
        placeholder: 'Select channel or enter ID',
      },
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
        placeholder: 'Enter message ID',
      },
    ],
  },

  add_reaction: {
    type: 'add_reaction',
    label: 'Add Reaction',
    category: 'messages',
    description: 'Add a reaction to a message',
    icon: 'Heart',
    color: '#EC4899',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'channel_select',
        required: true,
        placeholder: 'Select channel or enter ID',
      },
      {
        key: 'messageId',
        label: 'Message ID',
        type: 'text',
        required: true,
        placeholder: 'Enter message ID',
      },
      {
        key: 'emoji',
        label: 'Emoji',
        type: 'text',
        required: true,
        placeholder: 'Enter emoji (e.g., 😄, :thumbsup:, ⭐)',
      },
    ],
  },

  create_invite: {
    type: 'invite_create',
    label: 'Create Invite',
    category: 'channels',
    description: 'Create an invite link for a channel',
    icon: 'Link',
    color: '#10B981',
    inputs: 1,
    outputs: 1,
    properties: [
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'channel_select',
        required: true,
        placeholder: 'Select channel or enter ID',
      },
      {
        key: 'maxUses',
        label: 'Max Uses',
        type: 'number',
        required: false,
        defaultValue: 0,
        validation: { min: 0, max: 100000 },
        helperText: '0 for unlimited',
      },
      {
        key: 'maxAge',
        label: 'Max Age (seconds)',
        type: 'number',
        required: false,
        defaultValue: 86400,
        validation: { min: 0, max: 604800 },
        helperText: '0 for permanent, max 7 days',
      },
    ],
  },

  // Duplicates removed
}

// ============================================================================
// BLOCK CATEGORIES
// ============================================================================

export const BLOCK_CATEGORIES = [
  { id: 'triggers', label: 'Triggers', icon: 'Zap', color: '#5865F2', order: 1 },
  { id: 'events', label: 'Events', icon: 'Radio', color: '#57F287', order: 2 },
  { id: 'actions', label: 'Actions', icon: 'Play', color: '#5865F2', order: 3 },
  { id: 'messages', label: 'Messages', icon: 'MessageSquare', color: '#3B82F6', order: 4 },
  { id: 'embeds', label: 'Embeds', icon: 'Layout', color: '#E91E63', order: 5 },
  { id: 'components', label: 'Components', icon: 'MousePointer', color: '#F472B6', order: 6 },
  { id: 'moderation', label: 'Moderation', icon: 'Shield', color: '#EF4444', order: 7 },
  { id: 'roles', label: 'Roles', icon: 'Users', color: '#10B981', order: 8 },
  { id: 'channels', label: 'Channels', icon: 'Hash', color: '#8B5CF6', order: 9 },
  { id: 'voice', label: 'Voice', icon: 'Mic', color: '#E91E63', order: 10 },
  { id: 'logic', label: 'Logic', icon: 'GitBranch', color: '#8B5CF6', order: 11 },
  { id: 'variables', label: 'Variables', icon: 'Database', color: '#14B8A6', order: 12 },
  { id: 'data', label: 'Data & API', icon: 'Database', color: '#607D8B', order: 13 },
  { id: 'api', label: 'API', icon: 'Globe', color: '#6366F1', order: 14 },
  { id: 'database', label: 'Database', icon: 'Database', color: '#14B8A6', order: 15 },
  { id: 'utilities', label: 'Utilities', icon: 'Tool', color: '#6B7280', order: 16 },
  { id: 'debugging', label: 'Debugging', icon: 'Bug', color: '#EF4444', order: 17 },
  { id: 'advanced', label: 'Advanced', icon: 'Zap', color: '#8B5CF6', order: 18 },
]
